version: "3"
services:
  database:
    image: captainfact/dev-db:latest
    volumes: ["./__db_data:/var/lib/postgresql/data/captainfactdb"]
    environment:
      PGDATA: /var/lib/postgresql/data/captainfactdb
  graphql-api:
    image: captainfact/graphql-api:dev
    command: foreground
    ports: ["4002:4002", "4003:4003"]
    depends_on: [database]
    environment:
      CF_DB_HOSTNAME: database
