version: "3.1"
services:
  database:
    image: "postgres:9.6"
    volumes: ["./db:/var/lib/postgresql/data/captainfactdb"]
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "captain_fact_dev"
      PGDATA: /var/lib/postgresql/data/captainfactdb
  graphql-api:
    image: captainfact/graphql-api:dev
    command: foreground
    ports: ["4002:4002", "4003:4003"]
    depends_on: [database]
    environment:
      MIX_ENV: "prod"
      CF_HOST: "staging.captainfact.io"
      CF_DB_HOSTNAME: "database"
